### ISSUE TITLE
Always Restarting after `docker-compose up -d`

### ISSUE THREAD

**Issue by totemofwolf** [smehrbrodt/nextcloud-libreoffice-online#3]
----
➜ git clone https://github.com/smehrbrodt/nextcloud-libreoffice-online.git
➜ cd nextcloud-libreoffice-online/libreoffice-online
➜ cp -af .env.sample .env
➜ docker-compose up -d

➜  libreoffice-online git:(master) docker ps
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                            PORTS               NAMES
d9add862df82        libreoffice/online:master   "/bin/sh -c 'bash /r…"   4 minutes ago       Restarting (134) 55 seconds ago                       libreoffice-online_online_1

-----

Can't open /etc/loolwsd/loolwsd.xml: No such file or directory.
Can't open /etc/loolwsd/loolwsd.xml: No such file or directory.
Can't open /etc/loolwsd/loolwsd.xml: No such file or directory.
Setting up watches.
Couldn't watch /etc/loolwsd/loolwsd.xml: No such file or directory
ls: cannot access '/etc/loolwsd/loolwsd.xml': No such file or directory
 modified --> restarting
loolwsd: no process found
wsd-00018-00018 2019-05-22 09:57:03.256093 [ loolwsd ] INF  Initializing wsd. Local time: Wed 2019-05-22 09:57:03+0000. Log level is [8].| common/Log.cpp:199
wsd-00018-00018 2019-05-22 09:57:03.256173 [ loolwsd ] INF  Setting log-level to [trace] and delaying setting to configured [warning] until after WSD initialization.| wsd/LOOLWSD.cpp:931
wsd-00018-00018 2019-05-22 09:57:03.256216 [ loolwsd ] WRN  SSL support: SSL is disabled.| wsd/LOOLWSD.cpp:1018
wsd-00018-00018 2019-05-22 09:57:03.256250 [ loolwsd ] INF  NumPreSpawnedChildren set to 1.| wsd/LOOLWSD.cpp:1044
wsd-00018-00018 2019-05-22 09:57:03.256283 [ loolwsd ] INF  MAX_CONCURRENCY set to 4.| wsd/LOOLWSD.cpp:1052
wsd-00018-00018 2019-05-22 09:57:03.256316 [ loolwsd ] INF  Maximum concurrent open Documents limit: 10| wsd/LOOLWSD.cpp:1124
wsd-00018-00018 2019-05-22 09:57:03.256374 [ loolwsd ] INF  Maximum concurrent client Connections limit: 20| wsd/LOOLWSD.cpp:1125
wsd-00018-00018 2019-05-22 09:57:03.256413 [ loolwsd ] TRC  Pre-reading directory: /usr/share/loolwsd/loleaflet/dist| wsd/FileServer.cpp:461
Can't open /etc/loolwsd/loolwsd.xml: No such file or directory.
Can't open /etc/loolwsd/loolwsd.xml: No such file or directory.
Can't open /etc/loolwsd/loolwsd.xml: No such file or directory.
Setting up watches.
Couldn't watch /etc/loolwsd/loolwsd.xml: No such file or directory
ls: cannot access '/etc/loolwsd/loolwsd.xml': No such file or directory
 modified --> restarting
loolwsd: no process found
wsd-00016-00016 2019-05-22 09:57:29.783450 [ loolwsd ] INF  Initializing wsd. Local time: Wed 2019-05-22 09:57:29+0000. Log level is [8].| common/Log.cpp:199
wsd-00016-00016 2019-05-22 09:57:29.783621 [ loolwsd ] INF  Setting log-level to [trace] and delaying setting to configured [warning] until after WSD initialization.| wsd/LOOLWSD.cpp:931
wsd-00016-00016 2019-05-22 09:57:29.783697 [ loolwsd ] WRN  SSL support: SSL is disabled.| wsd/LOOLWSD.cpp:1018
wsd-00016-00016 2019-05-22 09:57:29.783794 [ loolwsd ] INF  NumPreSpawnedChildren set to 1.| wsd/LOOLWSD.cpp:1044
wsd-00016-00016 2019-05-22 09:57:29.783871 [ loolwsd ] INF  MAX_CONCURRENCY set to 4.| wsd/LOOLWSD.cpp:1052
wsd-00016-00016 2019-05-22 09:57:29.783929 [ loolwsd ] INF  Maximum concurrent open Documents limit: 10| wsd/LOOLWSD.cpp:1124
wsd-00016-00016 2019-05-22 09:57:29.783962 [ loolwsd ] INF  Maximum concurrent client Connections limit: 20| wsd/LOOLWSD.cpp:1125
wsd-00016-00016 2019-05-22 09:57:29.784062 [ loolwsd ] TRC  Pre-reading directory: /usr/share/loolwsd/loleaflet/dist| wsd/FileServer.cpp:461

**Comment by smehrbrodt** [comment]
Ah the docker image is broken at the moment, please wait a few hours until a new image is created.

**Comment by smehrbrodt** [comment]
New docker image uploaded, please try again.

**Comment by totemofwolf** [comment]
it works. btw 

```
When nextcloud is set up, install the App "Collabora Online". Then go to Configuration->Collabora Online and enter the domain name of your other VM, e.g. http://libreoffice.yourhost:9980
```

How to download the app "Collabora Online" and setting thing? I can not find the right way...

**Comment by facorazza** [comment]
> ➜ git clone https://github.com/smehrbrodt/nextcloud-libreoffice-online.git
> ➜ cd nextcloud-libreoffice-online/libreoffice-online
> ➜ cp -af .env.sample .env
> ➜ docker-compose up -d
> 
> ➜ libreoffice-online git:(master) docker ps
> CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
> d9add862df82 libreoffice/online:master "/bin/sh -c 'bash /r…" 4 minutes ago Restarting (134) 55 seconds ago libreoffice-online_online_1
> 
> Can't open /etc/loolwsd/loolwsd.xml: No such file or directory.
> Can't open /etc/loolwsd/loolwsd.xml: No such file or directory.
> Can't open /etc/loolwsd/loolwsd.xml: No such file or directory.
> Setting up watches.
> Couldn't watch /etc/loolwsd/loolwsd.xml: No such file or directory
> ls: cannot access '/etc/loolwsd/loolwsd.xml': No such file or directory
> modified --> restarting
> loolwsd: no process found
> wsd-00018-00018 2019-05-22 09:57:03.256093 [ loolwsd ] INF Initializing wsd. Local time: Wed 2019-05-22 09:57:03+0000. Log level is [8].| common/Log.cpp:199
> wsd-00018-00018 2019-05-22 09:57:03.256173 [ loolwsd ] INF Setting log-level to [trace] and delaying setting to configured [warning] until after WSD initialization.| wsd/LOOLWSD.cpp:931
> wsd-00018-00018 2019-05-22 09:57:03.256216 [ loolwsd ] WRN SSL support: SSL is disabled.| wsd/LOOLWSD.cpp:1018
> wsd-00018-00018 2019-05-22 09:57:03.256250 [ loolwsd ] INF NumPreSpawnedChildren set to 1.| wsd/LOOLWSD.cpp:1044
> wsd-00018-00018 2019-05-22 09:57:03.256283 [ loolwsd ] INF MAX_CONCURRENCY set to 4.| wsd/LOOLWSD.cpp:1052
> wsd-00018-00018 2019-05-22 09:57:03.256316 [ loolwsd ] INF Maximum concurrent open Documents limit: 10| wsd/LOOLWSD.cpp:1124
> wsd-00018-00018 2019-05-22 09:57:03.256374 [ loolwsd ] INF Maximum concurrent client Connections limit: 20| wsd/LOOLWSD.cpp:1125
> wsd-00018-00018 2019-05-22 09:57:03.256413 [ loolwsd ] TRC Pre-reading directory: /usr/share/loolwsd/loleaflet/dist| wsd/FileServer.cpp:461
> Can't open /etc/loolwsd/loolwsd.xml: No such file or directory.
> Can't open /etc/loolwsd/loolwsd.xml: No such file or directory.
> Can't open /etc/loolwsd/loolwsd.xml: No such file or directory.
> Setting up watches.
> Couldn't watch /etc/loolwsd/loolwsd.xml: No such file or directory
> ls: cannot access '/etc/loolwsd/loolwsd.xml': No such file or directory
> modified --> restarting
> loolwsd: no process found
> wsd-00016-00016 2019-05-22 09:57:29.783450 [ loolwsd ] INF Initializing wsd. Local time: Wed 2019-05-22 09:57:29+0000. Log level is [8].| common/Log.cpp:199
> wsd-00016-00016 2019-05-22 09:57:29.783621 [ loolwsd ] INF Setting log-level to [trace] and delaying setting to configured [warning] until after WSD initialization.| wsd/LOOLWSD.cpp:931
> wsd-00016-00016 2019-05-22 09:57:29.783697 [ loolwsd ] WRN SSL support: SSL is disabled.| wsd/LOOLWSD.cpp:1018
> wsd-00016-00016 2019-05-22 09:57:29.783794 [ loolwsd ] INF NumPreSpawnedChildren set to 1.| wsd/LOOLWSD.cpp:1044
> wsd-00016-00016 2019-05-22 09:57:29.783871 [ loolwsd ] INF MAX_CONCURRENCY set to 4.| wsd/LOOLWSD.cpp:1052
> wsd-00016-00016 2019-05-22 09:57:29.783929 [ loolwsd ] INF Maximum concurrent open Documents limit: 10| wsd/LOOLWSD.cpp:1124
> wsd-00016-00016 2019-05-22 09:57:29.783962 [ loolwsd ] INF Maximum concurrent client Connections limit: 20| wsd/LOOLWSD.cpp:1125
> wsd-00016-00016 2019-05-22 09:57:29.784062 [ loolwsd ] TRC Pre-reading directory: /usr/share/loolwsd/loleaflet/dist| wsd/FileServer.cpp:461

I'm still getting the same error

**Comment by ya-d** [comment]
> I'm still getting the same error

Same for me unfortunately.
