### ISSUE TITLE
libreoffice-online docker container restart over and over again

### ISSUE THREAD

**Issue by chunzhenzyd** [smehrbrodt/nextcloud-libreoffice-online#6]
{"log":"Generating RSA private key, 2048 bit long modulus (2 primes)\n","stream":"stderr","time":"2019-07-23T07:07:55.931311002Z"}
{"log":"......+++++\n","stream":"stderr","time":"2019-07-23T07:07:55.944209744Z"}
{"log":"................+++++\n","stream":"stderr","time":"2019-07-23T07:07:55.974082787Z"}
{"log":"e is 65537 (0x010001)\n","stream":"stderr","time":"2019-07-23T07:07:55.974334113Z"}
{"log":"Generating RSA private key, 2048 bit long modulus (2 primes)\n","stream":"stderr","time":"2019-07-23T07:07:55.987797016Z"}
{"log":"...............................................................................................+++++\n","stream":"stderr","time":"2019-07-23T07:07:56.150004861Z"}
{"log":"...+++++\n","stream":"stderr","time":"2019-07-23T07:07:56.157774908Z"}
{"log":"e is 65537 (0x010001)\n","stream":"stderr","time":"2019-07-23T07:07:56.158020959Z"}
{"log":"Signature ok\n","stream":"stderr","time":"2019-07-23T07:07:56.170218096Z"}
{"log":"subject=C = DE, ST = BW, L = Stuttgart, O = Dummy Authority, CN = localhost\n","stream":"stderr","time":"2019-07-23T07:07:56.170247016Z"}
{"log":"Getting CA Private Key\n","stream":"stderr","time":"2019-07-23T07:07:56.170465841Z"}
{"log":"Can't remove /etc/loolwsd/loolwsd.xml: Device or resource busy, skipping file.\n","stream":"stderr","time":"2019-07-23T07:07:56.183589008Z"}
{"log":"Can't remove /etc/loolwsd/loolwsd.xml: Device or resource busy, skipping file.\n","stream":"stderr","time":"2019-07-23T07:07:56.186280206Z"}
{"log":"Can't remove /etc/loolwsd/loolwsd.xml: Device or resource busy, skipping file.\n","stream":"stderr","time":"2019-07-23T07:07:56.188874144Z"}
{"log":"Setting up watches.\n","stream":"stderr","time":"2019-07-23T07:07:56.191403131Z"}
{"log":"Watches established.\n","stream":"stderr","time":"2019-07-23T07:07:56.191555683Z"}
{"log":"wsd-00028-00028 2019-07-23 07:07:56.257358 [ loolwsd ] INF  Initializing wsd. Local time: Tue 2019-07-23 15:07:56+0800. Log level is [8].| common/Log.cpp:199\n","stream":"stderr","time":"2019-07-23T07:07:56.25750803Z"}
{"log":"wsd-00028-00028 2019-07-23 07:07:56.257392 [ loolwsd ] INF  Setting log-level to [trace] and delaying setting to configured [warning] until after WSD initialization.| wsd/LOOLWSD.cpp:933\n","stream":"stderr","time":"2019-07-23T07:07:56.257544957Z"}
{"log":"wsd-00028-00028 2019-07-23 07:07:56.257422 [ loolwsd ] WRN  SSL support: SSL is disabled.| wsd/LOOLWSD.cpp:1020\n","stream":"stderr","time":"2019-07-23T07:07:56.257551306Z"}
{"log":"wsd-00028-00028 2019-07-23 07:07:56.257443 [ loolwsd ] INF  NumPreSpawnedChildren set to 5.| wsd/LOOLWSD.cpp:1046\n","stream":"stderr","time":"2019-07-23T07:07:56.257597662Z"}
{"log":"wsd-00028-00028 2019-07-23 07:07:56.257457 [ loolwsd ] INF  MAX_CONCURRENCY set to 4.| wsd/LOOLWSD.cpp:1054\n","stream":"stderr","time":"2019-07-23T07:07:56.257605265Z"}
{"log":"wsd-00028-00028 2019-07-23 07:07:56.257469 [ loolwsd ] INF  Maximum concurrent open Documents limit: 10| wsd/LOOLWSD.cpp:1126\n","stream":"stderr","time":"2019-07-23T07:07:56.257610415Z"}
{"log":"wsd-00028-00028 2019-07-23 07:07:56.257476 [ loolwsd ] INF  Maximum concurrent client Connections limit: 20| wsd/LOOLWSD.cpp:1127\n","stream":"stderr","time":"2019-07-23T07:07:56.257615515Z"}
{"log":"wsd-00028-00028 2019-07-23 07:07:56.257490 [ loolwsd ] TRC  Pre-reading directory: /usr/share/loolwsd/loleaflet/dist| wsd/FileServer.cpp:461\n","stream":"stderr","time":"2019-07-23T07:07:56.257620564Z"}
{"log":"wsd-00028-00028 2019-07-23 07:07:56.257559 [ loolwsd ] TRC  Reading file: '/usr/share/loolwsd/loleaflet/dist/bundle.css as '/loleaflet/dist/bundle.css'| wsd/FileServer.cpp:480\n","stream":"stderr","time":"2019-07-23T07:07:56.257625659Z"}
{"log":"wsd-00028-00028 2019-07-23 07:07:56.269769 [ loolwsd ] TRC  Pre-reading directory: /usr/share/loolwsd/loleaflet/dist/images| wsd/FileServer.cpp:461\n","stream":"stderr","time":"2019-07-23T07:07:56.269931092Z"}
{"log":"wsd-00028-00028 2019-07-23 07:07:56.270000 [ loolwsd ] TRC  Reading file: '/usr/share/loolwsd/loleaflet/dist/images/icon-set-grayarrows-up.svg as '/loleaflet/dist/images/icon-set-grayarrows-up.svg'| wsd/FileServer.cpp:480\n","stream":"stderr","time":"2019-07-23T07:07:56.270036118Z"}
{"log":"wsd-00028-00028 2019-07-23 07:07:56.270099 [ loolwsd ] TRC  Reading file: '/usr/share/loolwsd/loleaflet/dist/images/lc_starshapes.star24.svg as '/loleaflet/dist/images/lc_starshapes.star24.svg'| wsd/FileServer.cpp:480\n","stream":"stderr","time":"2019-07-23T07:07:56.270130303Z"}
.....
.....
.....
.....
.....
.....
.....
.....
.....
{"log":"wsd-00028-00028 2019-07-23 07:07:56.651137 [ loolwsd ] INF  Adding trusted WOPI host: [10\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}].| wsd/Storage.cpp:106\n","stream":"stderr","time":"2019-07-23T07:07:56.65117856Z"}
{"log":"wsd-00028-00028 2019-07-23 07:07:56.651160 [ loolwsd ] INF  Adding trusted WOPI host: [172\\.1[6789]\\.[0-9]{1,3}\\.[0-9]{1,3}].| wsd/Storage.cpp:106\n","stream":"stderr","time":"2019-07-23T07:07:56.651212354Z"}
{"log":"wsd-00028-00028 2019-07-23 07:07:56.651171 [ loolwsd ] INF  Adding trusted WOPI host: [172\\.2[0-9]\\.[0-9]{1,3}\\.[0-9]{1,3}].| wsd/Storage.cpp:106\n","stream":"stderr","time":"2019-07-23T07:07:56.651220243Z"}
{"log":"wsd-00028-00028 2019-07-23 07:07:56.651182 [ loolwsd ] INF  Adding trusted WOPI host: [172\\.3[01]\\.[0-9]{1,3}\\.[0-9]{1,3}].| wsd/Storage.cpp:106\n","stream":"stderr","time":"2019-07-23T07:07:56.651225813Z"}
{"log":"wsd-00028-00028 2019-07-23 07:07:56.651192 [ loolwsd ] INF  Adding trusted WOPI host: [192\\.168\\.[0-9]{1,3}\\.[0-9]{1,3}].| wsd/Storage.cpp:106\n","stream":"stderr","time":"2019-07-23T07:07:56.651260613Z"}
{"log":"wsd-00028-00028 2019-07-23 07:07:56.651203 [ loolwsd ] INF  Adding blocked WOPI host: [192\\.168\\.1\\.1].| wsd/Storage.cpp:111\n","stream":"stderr","time":"2019-07-23T07:07:56.651267932Z"}
{"log":"wsd-00028-00028 2019-07-23 07:07:56.651579 [ loolwsd ] INF  AdminModel ctor.| wsd/AdminModel.hpp:230\n","stream":"stderr","time":"2019-07-23T07:07:56.651623479Z"}
{"log":"wsd-00028-00028 2019-07-23 07:07:56.651594 [ loolwsd ] INF  Admin ctor.| wsd/Admin.cpp:360\n","stream":"stderr","time":"2019-07-23T07:07:56.651631629Z"}
{"log":"wsd-00028-00028 2019-07-23 07:07:56.651639 [ loolwsd ] TRC  Total system memory:  3931960 KB.| wsd/Admin.cpp:363\n","stream":"stderr","time":"2019-07-23T07:07:56.651681118Z"}
{"log":"wsd-00028-00028 2019-07-23 07:07:56.651748 [ loolwsd ] TRC  Total available memory: 3145568 KB (memproportion: 80%).| wsd/Admin.cpp:370\n","stream":"stderr","time":"2019-07-23T07:07:56.651805184Z"}
{"log":"wsd-00028-00028 2019-07-23 07:07:56.653089 [ loolwsd ] TRC  Total memory used: 24659 KB.| wsd/Admin.cpp:373\n","stream":"stderr","time":"2019-07-23T07:07:56.653147553Z"}
{"log":"wsd-00028-00028 2019-07-23 07:07:56.653156 [ loolwsd ] INF  Loolwsd version details: master.. - 73f83916 - id 09d8c18a| wsd/LOOLWSD.cpp:3154\n","stream":"stderr","time":"2019-07-23T07:07:56.653186584Z"}
{"log":"wsd-00028-00028 2019-07-23 07:07:56.653556 [ loolwsd ] INF  Registering filesystem for space checks: [/opt/lool/child-roots/.]| common/FileUtil.cpp:206\n","stream":"stderr","time":"2019-07-23T07:07:56.653657587Z"}
{"log":"wsd-00028-00028 2019-07-23 07:07:56.653593 [ loolwsd ] DBG  FileServerRoot: /usr/share/loolwsd| wsd/LOOLWSD.cpp:3193\n","stream":"stderr","time":"2019-07-23T07:07:56.653674534Z"}
{"log":"wsd-00028-00028 2019-07-23 07:07:56.656544 [ loolwsd ] DBG  #17 Thread affinity set to 0x7f25b7fd5580.| ./net/Socket.hpp:322\n","stream":"stderr","time":"2019-07-23T07:07:56.657415507Z"}
{"log":"wsd-00028-00028 2019-07-23 07:07:56.656587 [ loolwsd ] TRC  Bind to location loolwsd-PTt8neUO result - 0errno: no error| net/Socket.cpp:622\n","stream":"stderr","time":"2019-07-23T07:07:56.65744497Z"}
{"log":"wsd-00028-00028 2019-07-23 07:07:56.656600 [ loolwsd ] INF  Listening to prisoner connections on loolwsd-PTt8neUO| wsd/LOOLWSD.cpp:3053\n","stream":"stderr","time":"2019-07-23T07:07:56.657451713Z"}
{"log":"wsd-00028-00028 2019-07-23 07:07:56.656614 [ loolwsd ] DBG  Inserting socket #17 into prisoner_poll| ./net/Socket.hpp:663\n","stream":"stderr","time":"2019-07-23T07:07:56.65745702Z"}
{"log":"wsd-00028-00028 2019-07-23 07:07:56.656627 [ loolwsd ] DBG  #17 Thread affinity set to 0 (was 0x7f25b7fd5580).| ./net/Socket.hpp:282\n","stream":"stderr","time":"2019-07-23T07:07:56.65746207Z"}
{"log":"wsd-00028-00029 2019-07-23 07:07:56.656580 [ prisoner_poll ] INF  Thread 29 (7f25b438f700) is now called [prisoner_poll].| common/Util.cpp:522\n","stream":"stderr","time":"2019-07-23T07:07:56.657467058Z"}
{"log":"wsd-00028-00028 2019-07-23 07:07:56.656639 [ loolwsd ] TRC  Waiting for a new child for a max of 250000 ms.| wsd/LOOLWSD.cpp:3221\n","stream":"stderr","time":"2019-07-23T07:07:56.657472166Z"}
{"log":"wsd-00028-00029 2019-07-23 07:07:56.656661 [ prisoner_poll ] INF  Starting polling thread [prisoner_poll].| net/Socket.cpp:177\n","stream":"stderr","time":"2019-07-23T07:07:56.657477212Z"}
{"log":"wsd-00028-00029 2019-07-23 07:07:56.656674 [ prisoner_poll ] DBG  Thread affinity of prisoner_poll set to 0x7f25b438f700.| net/Socket.cpp:181\n","stream":"stderr","time":"2019-07-23T07:07:56.657482197Z"}
{"log":"wsd-00028-00029 2019-07-23 07:07:56.656697 [ prisoner_poll ] TRC  Poll start| ./net/Socket.hpp:511\n","stream":"stderr","time":"2019-07-23T07:07:56.657487256Z"}
{"log":"wsd-00028-00029 2019-07-23 07:07:56.656709 [ prisoner_poll ] TRC  Poll completed with 1 live polls max (5000ms)| ./net/Socket.hpp:521\n","stream":"stderr","time":"2019-07-23T07:07:56.657492091Z"}
{"log":"wsd-00028-00029 2019-07-23 07:07:56.656722 [ prisoner_poll ] DBG  #17 Thread affinity set to 0x7f25b438f700 (was 0).| ./net/Socket.hpp:282\n","stream":"stderr","time":"2019-07-23T07:07:56.657497131Z"}
{"log":"wsd-00028-00029 2019-07-23 07:07:56.656733 [ prisoner_poll ] TRC  PrisonerPoll - wakes up with 0 new children and 0 brokers and 0 kits forking| wsd/LOOLWSD.cpp:1521\n","stream":"stderr","time":"2019-07-23T07:07:56.657502107Z"}
{"log":"wsd-00028-00029 2019-07-23 07:07:56.656745 [ prisoner_poll ] INF  Creating new forkit process.| wsd/LOOLWSD.cpp:1564\n","stream":"stderr","time":"2019-07-23T07:07:56.657507332Z"}
{"log":"wsd-00028-00029 2019-07-23 07:07:56.656770 [ prisoner_poll ] INF  Launching forkit process: /usr/bin/loolforkit --losubpath=lo --systemplate=/opt/lool/systemplate --lotemplate=/opt/libreoffice --childroot=/opt/lool/child-roots/ --clientport=9980 --masterport=loolwsd-PTt8neUO --rlimits=limit_virt_mem_mb:0;limit_stack_mem_kb:8000;limit_file_size_mb:0;limit_num_open_files:0 --version| wsd/LOOLWSD.cpp:1632\n","stream":"stderr","time":"2019-07-23T07:07:56.657513402Z"}
{"log":"wsd-00028-00029 2019-07-23 07:07:56.657253 [ prisoner_poll ] INF  Forkit process launched: 30| wsd/LOOLWSD.cpp:1641\n","stream":"stderr","time":"2019-07-23T07:07:56.65752949Z"}
{"log":"wsd-00028-00029 2019-07-23 07:07:56.657297 [ prisoner_poll ] TRC  rebalance children to 4| wsd/LOOLWSD.cpp:416\n","stream":"stderr","time":"2019-07-23T07:07:56.6575345Z"}
{"log":"wsd-00028-00029 2019-07-23 07:07:56.657316 [ prisoner_poll ] TRC  rebalance children to 5| wsd/LOOLWSD.cpp:416\n","stream":"stderr","time":"2019-07-23T07:07:56.657549524Z"}
{"log":"wsd-00028-00029 2019-07-23 07:07:56.657329 [ prisoner_poll ] TRC  Poll start| ./net/Socket.hpp:511\n","stream":"stderr","time":"2019-07-23T07:07:56.657554907Z"}
{"log":"frk-00030-00030 2019-07-23 07:07:56.664498 [ forkit ] INF  Initializing frk. Local time: Tue 2019-07-23 15:07:56+0800. Log level is [8].| common/Log.cpp:199\n","stream":"stderr","time":"2019-07-23T07:07:56.664666156Z"}
{"log":"frk-00030-00030 2019-07-23 07:07:56.664521 [ forkit ] INF  Setting log-level to [trace] and delaying setting to configured [warning] until after Forkit initialization.| kit/ForKit.cpp:390\n","stream":"stderr","time":"2019-07-23T07:07:56.664700727Z"}
{"log":"frk-00030-00030 2019-07-23 07:07:56.664548 [ forkit ] INF  RLIMIT_AS is unlimited after setting it to unlimited.| common/Seccomp.cpp:250\n","stream":"stderr","time":"2019-07-23T07:07:56.664707074Z"}
{"log":"frk-00030-00030 2019-07-23 07:07:56.664562 [ forkit ] INF  RLIMIT_STACK is 8192000 bytes after setting it to 8192000 bytes.| common/Seccomp.cpp:250\n","stream":"stderr","time":"2019-07-23T07:07:56.66471232Z"}
{"log":"frk-00030-00030 2019-07-23 07:07:56.664570 [ forkit ] INF  Ignored setting RLIMIT_FSIZE to unlimited.| common/Seccomp.cpp:256\n","stream":"stderr","time":"2019-07-23T07:07:56.664717571Z"}
{"log":"frk-00030-00030 2019-07-23 07:07:56.664579 [ forkit ] INF  Ignored setting RLIMIT_NOFILE to unlimited.| common/Seccomp.cpp:256\n","stream":"stderr","time":"2019-07-23T07:07:56.664722416Z"}
{"log":"frk-00030-00030 2019-07-23 07:07:56.664604 [ forkit ] INF  Have capability cap_sys_chroot| kit/ForKit.cpp:182\n","stream":"stderr","time":"2019-07-23T07:07:56.664764633Z"}
{"log":"frk-00030-00030 2019-07-23 07:07:56.664613 [ forkit ] INF  Have capability cap_mknod| kit/ForKit.cpp:182\n","stream":"stderr","time":"2019-07-23T07:07:56.664772368Z"}
{"log":"frk-00030-00030 2019-07-23 07:07:56.664621 [ forkit ] INF  Have capability cap_fowner| kit/ForKit.cpp:182\n","stream":"stderr","time":"2019-07-23T07:07:56.664777577Z"}
{"log":"frk-00030-00030 2019-07-23 07:07:56.664686 [ forkit ] TRC  dlopen(/opt/libreoffice/program/libmergedlo.so, RTLD_GLOBAL|RTLD_NOW)| kit/Kit.cpp:2813\n","stream":"stderr","time":"2019-07-23T07:07:56.66478246Z"}
{"log":"loolforkit version details: master.. - 73f83916\n","stream":"stdout","time":"2019-07-23T07:07:56.664831628Z"}
{"log":"frk-00030-00030 2019-07-23 07:07:56.695309 [ forkit ] TRC  Invoking lok_preinit(/opt/libreoffice/program\", \"file:///user\")| kit/Kit.cpp:2867\n","stream":"stderr","time":"2019-07-23T07:07:56.695490533Z"}
{"log":"Init vcl\n","stream":"stderr","time":"2019-07-23T07:07:56.702169523Z"}
{"log":"preload: merged unordf ucpchelp1 msforms vbaobj pcr vbaswobj sw animcore hwp flash chartcore solver sc wpftcalc xof ucpcmis1 wpftdraw sd svgfilter evtatt graphicfilter wpftimpress sdfilt sm pdffilter PresentationMinimizer protocolhandler ucpdav1 wpftwriter msword lwpft writerfilter t602filter xmlfa basctl binaryurp uuresolver scd chartcontroller ldapbe2 dba sdbt deploymentgui migrationoo2 migrationoo3 xsltfilter sdd embobj emboleobj log expwrap odfflatxml textfd storagefd xmlfd frm fwl fwm io textconversiondlgs smd mozbootstrap oox scfilt slideshow proxyfac cairocanvas vclcanvas canvasfactory mtfrenderer simplecanvas oglcanvas dlgprov basprov stringresource dbaxml calc dbase flat writer reflection bootstrap introspection invocation invocadapt namingservice stocservices cached1 ucppkg1 srtrs1 ucptdoc1 xsltdlg swd cui bib guesslang numbertext offacc scn scriptframe dbpool2 xmlsecurity analysis date pricing i18nsearch xsec_xmlsec emfio vbaevents pdfimport mysql_jdbc pythonloader ucpext hyphen spell lnth for ctl passwordcontainer svgio\n","stream":"stderr","time":"2019-07-23T07:07:59.643143596Z"}
{"log":"Disabled: ucpftp1 rptxml dbu dbmm OGLTrans rptui rpt mork odbc sdbc2 mysqlc cmdmail syssh ucphier1 ucpimage fps_office PresenterScreen abp dbp updatefeed \n","stream":"stderr","time":"2019-07-23T07:07:59.643190216Z"}
{"log":"wsd-00028-00029 2019-07-23 07:08:01.659106 [ prisoner_poll ] TRC  Poll completed with 0 live polls max (5000ms)(timedout)| ./net/Socket.hpp:521\n","stream":"stderr","time":"2019-07-23T07:08:01.659304275Z"}
{"log":"wsd-00028-00029 2019-07-23 07:08:01.659178 [ prisoner_poll ] TRC  Poll start| ./net/Socket.hpp:511\n","stream":"stderr","time":"2019-07-23T07:08:01.659347827Z"}
{"log":"Whitelisted languages: de_DE en_GB en_US es_ES fr_FR it nl pt_BR pt_PT ru \n","stream":"stderr","time":"2019-07-23T07:08:04.329450475Z"}
{"log":"Preloading dictionaries: de_DE en_US fr_FR it_IT nl_NL pt_BR ru_RU en_GB nl_BE pt_PT es_ES \n","stream":"stderr","time":"2019-07-23T07:08:05.440659815Z"}
{"log":"Preloading thesauri: de_DE en_US fr_FR it_IT nl_NL pt_BR ru_RU en_GB nl_BE pt_PT es_ES \n","stream":"stderr","time":"2019-07-23T07:08:05.574861191Z"}
{"log":"Preload icons\n","stream":"stderr","time":"2019-07-23T07:08:05.575824376Z"}
{"log":"Preload languages\n","stream":"stderr","time":"2019-07-23T07:08:05.586282884Z"}
{"log":"Preload fonts\n","stream":"stderr","time":"2019-07-23T07:08:05.587840837Z"}
{"log":"frk-00030-00030 2019-07-23 07:08:06.009963 [ forkit ] TRC  Finished lok_preinit(/opt/libreoffice/program\", \"file:///user\") in 9314 ms.| kit/Kit.cpp:2877\n","stream":"stderr","time":"2019-07-23T07:08:06.010152245Z"}
{"log":"frk-00030-00030 2019-07-23 07:08:06.010039 [ forkit ] ERR  Error: forkit has more than a single thread after pre-init| kit/ForKit.cpp:546\n","stream":"stderr","time":"2019-07-23T07:08:06.010191526Z"}
{"log":"frk-00030-00030 2019-07-23 07:08:06.010050 [ forkit ] INF  Preinit stage OK.| kit/ForKit.cpp:548\n","stream":"stderr","time":"2019-07-23T07:08:06.010197567Z"}
{"log":"frk-00030-00030 2019-07-23 07:08:06.010081 [ forkit ] DBG  Forking a loolkit process with jailId: BNJd92dIYKcEvIZO.| kit/ForKit.cpp:253\n","stream":"stderr","time":"2019-07-23T07:08:06.010245186Z"}
{"log":"frk-00030-00030 2019-07-23 07:08:06.018935 [ forkit ] INF  Forked kit [32].| kit/ForKit.cpp:294\n","stream":"stderr","time":"2019-07-23T07:08:06.01914484Z"}
{"log":"frk-00030-00030 2019-07-23 07:08:06.019066 [ forkit ] INF  Forkit initialization complete: setting log-level to [warning] as configured.| kit/ForKit.cpp:565\n","stream":"stderr","time":"2019-07-23T07:08:06.019183465Z"}
{"log":"frk-00030-00030 2019-07-23 07:08:06.019429 [ loolkit ] INF  Thread 30 (7fcca1c26c80) is now called [loolkit].| common/Util.cpp:522\n","stream":"stderr","time":"2019-07-23T07:08:06.019579447Z"}
{"log":"kit-00032-00030 2019-07-23 07:08:06.019632 [ loolkit ] INF  Initializing kit. Local time: Tue 2019-07-23 15:08:06+0800. Log level is [8].| common/Log.cpp:199\n","stream":"stderr","time":"2019-07-23T07:08:06.01969451Z"}
{"log":"kit-00032-00030 2019-07-23 07:08:06.019658 [ loolkit ] INF  Setting log-level to [trace] and delaying setting to configured [warning] until after Kit initialization.| kit/Kit.cpp:2473\n","stream":"stderr","time":"2019-07-23T07:08:06.019750288Z"}
{"log":"kit-00032-00030 2019-07-23 07:08:06.019677 [ loolkit ] INF  Filename anonymization is disabled.| kit/Kit.cpp:2477\n","stream":"stderr","time":"2019-07-23T07:08:06.019758972Z"}
{"log":"kit-00032-00030 2019-07-23 07:08:06.019690 [ loolkit ] INF  Username anonymization is disabled.| kit/Kit.cpp:2479\n","stream":"stderr","time":"2019-07-23T07:08:06.019764643Z"}
{"log":"kit-00032-00030 2019-07-23 07:08:06.019697 [ loolkit ] DBG  Process started.| kit/Kit.cpp:2486\n","stream":"stderr","time":"2019-07-23T07:08:06.019769831Z"}
{"log":"kit-00032-00030 2019-07-23 07:08:06.019726 [ loolkit ] INF  Jail path: /opt/lool/child-roots/BNJd92dIYKcEvIZO/| kit/Kit.cpp:2506\n","stream":"stderr","time":"2019-07-23T07:08:06.019801718Z"}
{"log":"kit-00032-00030 2019-07-23 07:08:06.019976 [ loolkit ] DBG  symlink(\"../lo\",\"/opt/lool/child-roots/BNJd92dIYKcEvIZO/opt/libreoffice\")| kit/Kit.cpp:374\n","stream":"stderr","time":"2019-07-23T07:08:06.020043481Z"}
{"log":"wsd-00028-00029 2019-07-23 07:08:06.664253 [ prisoner_poll ] TRC  Poll completed with 0 live polls max (5000ms)(timedout)| ./net/Socket.hpp:521\n","stream":"stderr","time":"2019-07-23T07:08:06.664469206Z"}
{"log":"wsd-00028-00029 2019-07-23 07:08:06.664318 [ prisoner_poll ] TRC  Poll start| ./net/Socket.hpp:511\n","stream":"stderr","time":"2019-07-23T07:08:06.664517983Z"}
{"log":"wsd-00028-00029 2019-07-23 07:08:11.668185 [ prisoner_poll ] TRC  Poll completed with 0 live polls max (5000ms)(timedout)| ./net/Socket.hpp:521\n","stream":"stderr","time":"2019-07-23T07:08:11.668437432Z"}
{"log":"wsd-00028-00029 2019-07-23 07:08:11.668246 [ prisoner_poll ] TRC  Poll start| ./net/Socket.hpp:511\n","stream":"stderr","time":"2019-07-23T07:08:11.668467656Z"}
{"log":"wsd-00028-00029 2019-07-23 07:08:16.671055 [ prisoner_poll ] TRC  Poll completed with 0 live polls max (5000ms)(timedout)| ./net/Socket.hpp:521\n","stream":"stderr","time":"2019-07-23T07:08:16.6711706Z"}
{"log":"wsd-00028-00029 2019-07-23 07:08:16.671179 [ prisoner_poll ] TRC  Poll start| ./net/Socket.hpp:511\n","stream":"stderr","time":"2019-07-23T07:08:16.671216121Z"}
{"log":"wsd-00028-00029 2019-07-23 07:08:21.673756 [ prisoner_poll ] TRC  Poll completed with 0 live polls max (5000ms)(timedout)| ./net/Socket.hpp:521\n","stream":"stderr","time":"2019-07-23T07:08:21.673965408Z"}
{"log":"wsd-00028-00029 2019-07-23 07:08:21.673816 [ prisoner_poll ] TRC  Poll start| ./net/Socket.hpp:511\n","stream":"stderr","time":"2019-07-23T07:08:21.67399787Z"}
{"log":"wsd-00028-00029 2019-07-23 07:08:26.677614 [ prisoner_poll ] TRC  Poll completed with 0 live polls max (5000ms)(timedout)| ./net/Socket.hpp:521\n","stream":"stderr","time":"2019-07-23T07:08:26.67778332Z"}
{"log":"wsd-00028-00029 2019-07-23 07:08:26.677679 [ prisoner_poll ] TRC  Poll start| ./net/Socket.hpp:511\n","stream":"stderr","time":"2019-07-23T07:08:26.677829979Z"}
{"log":"kit-00032-00030 2019-07-23 07:08:26.983659 [ loolkit ] WRN  Linking/copying files from /opt/libreoffice to /opt/lool/child-roots/BNJd92dIYKcEvIZO/lo/ is taking too much time. Enabling verbose link/copy logging at information level.| kit/Kit.cpp:247\n","stream":"stderr","time":"2019-07-23T07:08:26.983876613Z"}
{"log":"kit-00032-00030 2019-07-23 07:08:26.983735 [ loolkit ] INF  Linking file \"/opt/libreoffice/share/gallery/bullets/Bullet26-X-Red.svg\" to \"/opt/lool/child-roots/BNJd92dIYKcEvIZO/lo/share/gallery/bullets/Bullet26-X-Red.svg\"| kit/Kit.cpp:213\n","stream":"stderr","time":"2019-07-23T07:08:26.983918618Z"}
{"log":"kit-00032-00030 2019-07-23 07:08:27.028681 [ loolkit ] INF  Linking file \"/opt/libreoffice/share/gallery/bullets/bludiamd.gif\" to \"/opt/lool/child-roots/BNJd92dIYKcEvIZO/lo/share/gallery/bullets/bludiamd.gif\"| kit/Kit.cpp:213\n","stream":"stderr","time":"2019-07-23T07:08:27.02884529Z"}

**Comment by smehrbrodt** [comment]
For support options check https://github.com/smehrbrodt/nextcloud-libreoffice-online#professional-support
